import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { AppService } from './app.service';

// Basic smoke test for the root controller — generated by the NestJS CLI.
// Only checks whether the GET / route returns 'Hello World!'.
describe('AppController', () => {
  let appController: AppController;

  beforeEach(async () => {
    // Test.createTestingModule() bootstraps an isolated NestJS module
    // without starting a real database or HTTP server.
    const app: TestingModule = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    }).compile();

    appController = app.get<AppController>(AppController);
  });

  describe('root', () => {
    it('should return "Hello World!"', () => {
      expect(appController.getHello()).toBe('Hello World!');
    });
  });
});
